version: "3.9"  # optional since v1.27.0
services:
    web_api_nexus:
        build: . # build the Docker image 
        image: storenexusapi.azurecr.io/store-nexus:latest
        container_name: web_api_nexus_store
        ports:
            - "80:80"
        depends_on:
            - sql
    sql:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        container_name: sql_server2017
        ports: # not actually needed, because the two services are on the same network
            - "1433:1433" 
        environment:
            - ACCEPT_EULA=y
            - SA_PASSWORD=A&VeryComplex123Password